// src/components/Footer.vue
<template>
  <footer 
    :class="[
      'w-full p-4 flex flex-col sm:flex-row justify-between items-center text-sm',
      isDarkMode ? 'bg-neutral-900 text-gray-300' : 'bg-white text-neutral-800'
    ]"
  >
    <div class="flex space-x-4 mb-4 sm:mb-0">
      <a href="https://linkedin.com/in/tocausan" target="_blank" class="hover:text-blue-500 transition">
        LinkedIn
      </a>
      <a href="https://github.com/tocausan" target="_blank" class="hover:text-blue-500 transition">
        GitHub
      </a>
      <a href="https://codepen.io/tocausan" target="_blank" class="hover:text-blue-500 transition">
        CodePen
      </a>
    </div>
    
    <div class="text-center text-xs">
      © {{ currentYear }} TCSN | All rights reserved
    </div>
  </footer>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  isDarkMode: boolean
}

defineProps<Props>()

const currentYear = computed(() => new Date().getFullYear())
</script>

// src/components/layout/Footer.tsx
/** @format */

import Config from '@/utils/Config'
import Link from "next/link";
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Codepen, Instagram, Mail } from "react-feather";
import { FaGithub, FaLinkedin, FaBehance, FaPinterest, } from "react-icons/fa";

export default function Footer () {
  const router = useRouter();
  const [ isDarkMode, setIsDarkMode ] = useState( false );

  useEffect( () => {
    switch( true ) {
      case router.pathname.includes( '/projects' ):
        setIsDarkMode( true );
        break;
      default:
        setIsDarkMode( false );
    }
  }, [ router.pathname ] );

  return (
    <footer className={ [
      'w-[100%] px-5 py-2 flex flex-col sm:flex-row justify-start items-center sm:justify-between relative z-10 ',
      isDarkMode ? 'bg-neutral-900 text-gray-300' : 'bg-white text-neutral-800'
    ].join( ' ' ) }>
      <div className='w-[100%] sm:w-[50%] flex flex-row justify-evenly sm:justify-start p-5 sm:p-0'>
        <Link href={ Config.social.github.url } title='tocausan@Github' target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-gray-600 transition">
          <FaGithub size={ 20 } />
        </Link>
        <Link href={ Config.social.codepen.url } title='tcsn@Codepen' target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-gray-600 transition">
          <Codepen size={ 20 } />
        </Link>
        <Link href={ Config.social.linkedin.url } title='tocausan@Linkedin' target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-blue-600 transition">
          <FaLinkedin size={ 20 } />
        </Link>
        <Link href={ Config.social.pinterest.url } title='tocausan@Pinterest' target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-red-600 transition">
          <FaPinterest size={ 20 } />
        </Link>
        <Link href={ Config.social.instagram.url } title='tocausan@Instagram' target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-pink-600 transition">
          <Instagram size={ 20 } />
        </Link>
        <Link href={ Config.social.behance.url } title='tocausan@Behance' target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-blue-600 transition">
          <FaBehance size={ 20 } />
        </Link>
        <Link href={ 'mailto:' + Config.email } title={ Config.email } target='_blank' rel='noreferrer' className="px-1 m-1 hover:text-cyan-600 transition">
          <Mail size={ 20 } />
        </Link>
      </div>

      <div className='w-[100%] text-[12px] pb-2 flex justify-center sm:justify-end items-end select-none'>
        <div className="">
          <Link href="/contact" rel='noreferrer' className="hover:text-cyan-600 transition">
            Contact
          </Link>
        </div>
        <div className="mx-2">|</div>
        <div className="">{ Config.copyright }</div>
        <div className="ml-1">{ new Date().getFullYear() }</div>
      </div>
    </footer>
  );
};
