// src/components/layout/Layout.vue
<template>
  <div>
    <SEO
      :title="props.title"
      :description="`TCSN ${props.title}`"
      site-title="TCSN"
    />
    <Header />
    <main class="w-full min-h-screen bg-gray-100 shadow-md z-10">
      <slot />
    </main>
    <Footer />
  </div>
</template>

<script setup>
import SEO from './SEO.vue'
import Header from './header/Header.vue'
import Footer from './Footer.vue'

const props = defineProps({
  title: {
    type: String,
    default: 'TCSN'
  }
})
</script>

// src/components/layout/Layout.tsx
// header component
import React from 'react';
import SEO from './SEO';
import Header from './header/Header';
import Footer from './Footer';

// layout component
export default function Layout({ title, children }: { title: string, children: React.ReactNode }) {
  return (
    <>
      <SEO title={title} description={'Tocausan' + title} siteTitle="Tocausan" />
      <Header />
      <main className='w-[100%] min-h-[100vh] bg-gray-100 shadow-md z-10'>
        {children}
      </main>
      <Footer />
    </>
  )
}
