// src/components/home/HomeIntro.vue
<template>
  <div class="home-intro w-full min-h-[20vh] py-8 flex flex-col justify-center items-center bg-gradient-to-b from-blue-50 to-blue-100">
    <div class="w-4/5 max-w-4xl p-5 flex flex-col sm:flex-row justify-between rounded-lg">
      <div class="text flex-1">
        <h1 class="home-intro-title text-4xl font-bold text-gray-900 mb-5">
          {{ title }}
        </h1>
        <p class="home-intro-description text-2xl text-gray-700 leading-relaxed">
          {{ description }}
        </p>
      </div>

      <div class="w-full sm:w-auto text-gray-900 flex justify-center mt-8 sm:mt-0 sm:ml-8">
        <router-link
          to="/contact"
          class="w-full sm:w-auto"
        >
          <button class="primary w-full sm:w-auto bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition-colors duration-300">
            Contact Us
          </button>
        </router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const title = ref('')
const description = ref('')

const content = {
  title: 'Creative Technology Studio',
  description: `
    We craft digital experiences that inspire and engage.
    From web applications to creative solutions,
    we bring your vision to life.
  `
}

onMounted(() => {
  title.value = content.title
  description.value = content.description
})
</script>

<style scoped>
.home-intro {
  transition: all 0.3s ease;
}

.primary {
  min-width: 150px;
}
</style>

// src/components/home/HomeIntro.tsx
import { useState, useEffect } from 'react'
import Link from "next/link";

export default function HomeIntro () {
  const [ title, setTitle ] = useState( '' )
  const [ description, setDescription ] = useState( '' )


  const content = {
    title: '',
    description: `
    Position: Full Stack Developer
    Location: Remote
    Availability: Open
    `

  }

  return (
    <>
      <div className='home-intro w-[100%] min-h-[20vh] py-[30px] flex flex-col justify-center align-center items-center bg-[#E5F7FF] bg-gradient-to-b from-[#E5F7FF] to-[#D5EFFC]'>
        <div className="w-[80%] max-w-[900px] p-5 flex flex-col sm:flex-row justify-between rounded-lg">

          <div className="text">
            <h1 className="home-intro-title text-4xl font-bold text-neutral-900">
              { title }
            </h1>
            <p className="home-intro-description text-2xl text-neutral-900 mt-5">
              { description }
            </p>
          </div>

          <div className="w-[100%] text-neutral-900 flex justify-center">
            <Link href="/contact" className='w-[100%]'>
              <button className="primary w-[100%]">
                Contact
              </button>
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}
